<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
	</array>
	<key>name</key>
	<string>Aruba Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Triggers on "hostname"</string>
			<key>match</key>
			<string>^version\s(.*)</string>
			<key>name</key>
			<string>version.aruba</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Triggers on "hostname"</string>
			<key>match</key>
			<string>(hostname)\s"(.*)"</string>
			<key>name</key>
			<string>hostname.aruba</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>netservice.name.aruba</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>netservice.proto.aruba</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>netservice.list.aruba</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>netservice.list.aruba</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>netservice.port.aruba</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>netservice.alg.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all netservice entries</string>
			<key>match</key>
			<string>^netservice\s([a-zA-Z0-9\-]*)\s([tcp|udp|([0-9]{1,3})]+)\s(((list\s)([\"0-9\s]*))*)(([0-9\s]{1,5})*)(((alg)\s.+)*)</string>
			<key>name</key>
			<string>netservice.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^netdestination(6*)\s(([a-zA-Z0-9\-\_])+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>netdest.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all netdestination entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>netdest.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^netexthdr\s(.*)</string>
			<key>comment</key>
			<string>Captures all netexthdr entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>netexthdr.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^time-range\s(.*)</string>
			<key>comment</key>
			<string>Captures all time-range entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>timerange.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ip\saccess-list\s(([a-zA-Z0-9\-\_])+)\s(([a-zA-Z0-9\-\_])+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>ip.acl.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all ip access-list entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>ip.acl.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^user-role\s([a-zA-Z0-9\-\_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>role.user.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all user-role entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>role.user.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^interface\s([a-z\-]+)\s(([0-9])+)(\/*)(([0-9]{1,2})*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>interface.name.aruba</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>interface.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all interface entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>interface.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^airgroup(service)?\s("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>airgroup.service.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all airgroup entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>airgroup.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ap\s(.*)\s("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>ap.profile.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all ap profile entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>ap.profile.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^rf\s(.*)\s("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>rf.profile.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all rf profile entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>rf.profile.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^wlan\s(.*)\s("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>wlan.profile.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all wlan profile entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>wlan.profile.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ap\-group\s(.*)("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>ap.group.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all ap-group entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>ap.group.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^ap\-name\s(.*)("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>ap.specific.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all ap-group entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>ap.specific.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^aaa\s(.*)\s("(.*)")</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>aaa.profile.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all aaa entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>aaa.profile.aruba</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^aaa\s(derivation-rules)\s(user)\s(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>aaa.profile.derivation.name.aruba</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Captures all aaa user-derivation entries</string>
			<key>end</key>
			<string>\!</string>
			<key>name</key>
			<string>aaa.profile.aruba</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ipaddr</key>
		<dict>
			<key>match</key>
			<string>\b(?:\d{1,3}\.){3}\d{1,3}\b</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.aruba</string>
	<key>uuid</key>
	<string>bcf827c8-b6fe-434a-8c83-35d186835bd7</string>
</dict>
</plist>
